language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO_VERSION=1.6.1
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.4.10
install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
script: coverage run runtests.py --with-spec
after_success:
  - coveralls --verbose
matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=1.4.10
    - python: 3.3
      env: DJANGO_VERSION=1.4.10
