language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=Django==1.4.20
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.2        

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=Django==1.4.20
    - python: "3.4"
      env: DJANGO=Django==1.4.20

install:
  - pip install -r requirements.txt $DJANGO   
  - pip install tox

script:
  - ./runtests.py
