language: python
python:
  - 2.7
env:
  - TOX_ENV=py27-1.4.x
  - TOX_ENV=py27-1.6.x
  - TOX_ENV=py33-1.6.x
  - TOX_ENV=py34-1.6.x
  - TOX_ENV=py27-1.7.x
  - TOX_ENV=py33-1.7.x
  - TOX_ENV=py34-1.7.x

install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls --verbose
