language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.5.1
  - DJANGO_VERSION=1.4.3
install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
script: coverage run runtests.py --with-spec
after_success:
  - coveralls --verbose
